version: 0.2

phases:
  pre_build:
    runtime-versions:
       nodejs: 12
    commands:
       - yarn
       - npm install next -g
  build:
    commands:
       - npx next build
artifacts:
  files:
     - '**/*'
